version: '3.8'

services:
  todo-app:
    image: hagersobhy728/nodejs-todo-app
    ports:
      - "4000:4000"
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    restart: always
