---
- name: Install Docker, Kubernetes, Git on CentOS
  hosts: all
  become: true

  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest

    - name: Install required packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - git
          - curl
        state: present

    # -------- Docker --------
    - name: Add Docker repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      yum:
        name: docker-ce
        state: latest

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: true
        state: started

    # -------- Kubernetes --------
    - name: Add Kubernetes repo
      copy:
        dest: /etc/yum.repos.d/kubernetes.repo
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
                 https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
          exclude=kubelet kubeadm kubectl

    - name: Install kubelet, kubeadm, kubectl
      yum:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        disable_excludes: kubernetes

    - name: Enable and start kubelet
      systemd:
        name: kubelet
        enabled: true
        state: started

    - name: Set SELinux to permissive mode (required by Kubernetes)
      selinux:
        state: permissive

    - name: Disable swap (required by kubeadm)
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Comment out swap in /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*swap)'
        replace: '# \1'
