apiVersion: v1
kind: Secret
metadata:
  name: todo-app-secret
type: Opaque
stringData:
  mongoDbUrl: "mongodb+srv://hagersmohammed728:D5pn7MwT73N6BxDu@cluster0.pjfmsrq.mongodb.net/todo"
  PORT: "4000"
