apiVersion: v1
kind: Secret
metadata:
  name: todo-app-secret
type: Opaque
stringData:
  mongoDbUrl: "mongodb://atlas-sql-68876bd35dcf761f47bd7fe8-xulcvf.a.query.mongodb.net/sample_mflix?ssl=true&authSource=admin"
  PORT: "4000"
